export const SET_DANH_SACH_PHIM ='SET_DANH_SACH_PHIM'
export const SET_FILM_DETAIL = 'SET_FILM_DETAIL'
export const SET_DANH_SACH_PHIM_DANG_CHIEU = 'SET_DANH_SACH_PHIM_DANG_CHIEU'
export const SET_DANH_SACH_PHIM_SAP_CHIEU = 'SET_DANH_SACH_PHIM_SAP_CHIEU'
